require("color")
require("plugins")
require("plugins/telescope")
require("plugins/nvim-tree")
require("plugins/lualine")
require("plugins/tokyonight")
require("plugins/treesitter")
require("plugins/autopairs")
require("plugins/comment")
require("plugins/bufferline")
require("plugins/gitsigns")
require("maps")
require("plugins/coc")
require("base")

-- require("plugins/cmp")
-- require("plugins/lsp")
-- require("plugins/null-ls")
-- require("plugins/prettier")
-- require("plugins/formatter")
