require("color")
require("maps")
require("plugins")
require("plugins/telescope")
require("plugins/nvim-tree")
require("plugins/lualine")
require("plugins/tokyonight")
require("plugins/treesitter")
require("plugins/autopairs")
require("plugins/comment")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/coc")
require("plugins/blankline")
-- require("plugins/diffview")
require("base")
